### ISSUE TITLE
how are these binaries built? where do they came from?

### ISSUE THREAD

**Issue by rgl** [electron-userland/electron-builder-binaries#1]
I'm trying to figure out from where the binaries that are inside this repository came from. For example, the Squirrel.Windows binaries that are inside this repo don't match the [official 1.5.1 binaries](https://github.com/Squirrel/Squirrel.Windows/releases/tag/1.5.1). there's missing files (e.g. `StubExecutable.exe`) and extraneous files (e.g. `.pdb` files). What is going on?

**Comment by develar** [comment]
Update procedure:

1. Merge changes from upstream to https://github.com/develar/Squirrel.Windows
1.1 Ensure that pack implementation on electron-builder side is up to date.
2. Grab artifacts from CI server: https://ci.appveyor.com/project/develar/squirrel-windows
3. Upload to bintray using `squirrelWindows.sh`
4. Change SHA2 checksum and version in the https://github.com/electron-userland/electron-builder/blob/master/src/targets/squirrelWindows.ts#L12

Step 1.1 was skipped during update to 1.5.1
