### ISSUE TITLE
Support to sign MSI in linux

### ISSUE THREAD

**Issue by yarcub** [electron-userland/electron-builder-binaries#10]
I'm using docker to build and sign `msi` target and getting the following error:
```
Failed
libgsf is not available, msi support is disabled: /usr/src/app/dist/myapp-electron-ia32.msi
```

I see that the msi signing is supported in [`osslsigncode 1.7.1`](https://github.com/develar/osslsigncode/blob/master/ChangeLog) but couldn't find out which version of the binary is included for linux builds. Only that the one in this repo was updated ~2y ago and the one for darwin was updated more recently.

Adding support for it would be building the linux binary https://github.com/develar/osslsigncode and open a PR? Any hints?

Thanks.

**Comment by techterbium** [comment]
Hello there, can someone help me with how to resolve this?

**Comment by shrinidhi111** [comment]
@techterbium It appears that that dependency is no longer required osslsigncode 2.2+

**Comment by shrinidhi111** [comment]
https://github.com/mtrojnar/osslsigncode/releases
