### ISSUE TITLE
Question - How to use this binaries

### ISSUE THREAD

**Issue by myfrndjk** [electron-userland/electron-builder-binaries#4]
Hi,

Can I download this binary  and use this to build my application without installing anything.
For example in my app package.json mention under script.

"pack" : electron-builder-binaries/nsis.sh
will above line convert my code to exe file.

I am not sure how to use this binary and cant find any documentation or wiki.
What is the exact use of this binaries.

Thanks
Jk

**Comment by develar** [comment]
Please see readme — please use electron-builder to build electron application.
