### ISSUE TITLE
[Feature request] Downgrade Wixtoolset to v3 (3.14)

### ISSUE THREAD

**Issue by GeekCornerGH** [electron-userland/electron-builder-binaries#43]
I wanted to build my Electron app for arm64, with msi format, but the version you are using doesn't support arm64. Wix toolset v3.14 supports arm64. Can you change it? Thank you.
I posted this request in electron-userland/electron-builder#6077 but acording to @mmaietta (read https://github.com/electron-userland/electron-builder/issues/6077#issuecomment-886067529), the issue would be more useful there.

**Comment by mrksr** [comment]
I just ran into the exact same issue. Adding to the info provided by @GeekCornerGH and according to https://github.com/wixtoolset/issues/issues/6513, the WiX v4-preview.0 version also supports arm64. I'd expect any newer version of wix4 to support it as well.
