### ISSUE TITLE
AppImage mksquashfs binary does not support LZO compression

### ISSUE THREAD

**Issue by om26er** [electron-userland/electron-builder-binaries#45]
The `mksquashfs` binary is too old (https://github.com/electron-userland/electron-builder-binaries/blob/master/AppImage/linux-x64/mksquashfs), it does not support lzo compression, please build it with LZO compression and publish a new version.

Background: I am trying to enable electron-builder to support LZO compression for snap packages https://github.com/electron-userland/electron-builder/pull/6201 and I recently found that electron builder internally uses the `mksquashfs` binary from this repository. Below are the logs
```
om26er@RemotePC:~/scm/ubuntu/electron-quick-start$ node /home/om26er/scm/ubuntu/electron-builder/packages/electron-builder/cli.js -l snap
  • electron-builder  version=22.13.1 os=5.11.0-31-generic
  • loaded configuration  file=/home/om26er/scm/ubuntu/electron-quick-start/electron-builder.yml
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=11.4.12 appOutDir=dist/linux-unpacked
  • building        target=snap arch=x64 file=dist/electron-quick-start_1.0.0_amd64.snap
  • default Electron icon is used  reason=application icon is not set
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  ⨯ cannot execute  cause=exit status 1
                    errorOut=/home/om26er/.cache/electron-builder/appimage/appimage-12.0.1/linux-x64/mksquashfs: Compressor "lzo" is not supported!
    /home/om26er/.cache/electron-builder/appimage/appimage-12.0.1/linux-x64/mksquashfs: Compressors available:
        gzip (default)
        xz
```

**Comment by om26er** [comment]
Binary needs to be built with LZO_SUPPORT=1 https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/Makefile#L51

**Comment by om26er** [comment]
ping maintainers, is there a way I could help fix that ?

**Comment by develar** [comment]
Built with `XZ_SUPPORT=1 LZO_SUPPORT=1 ZSTD_SUPPORT=1 GZIP_SUPPORT=0 COMP_DEFAULT=zstd`.
